# Sidebar navigation

- label: "Introduction"
  link: "/"

- label: "Hello World"
  items:
    - label: "Getting Started"
      link: "/hello-world/intro"
    - label: "A simple web server"
      link: "/hello-world/web-server"

- label: "More HTTP"
  items:
    - label: "Introduction"
      link: "/http/intro"
    - label: "Hello Oak"
      link: "/http/hello-oak"
    - label: "Routing"
      link: "/http/routing-basics"
    - label: "Deep Dive into Routing"
      link: "/http/routing-advanced"
    - label: "Cookies"
      link: "/http/routing-advanced"
    - label: "Middleware"
      link: "/http/routing-advanced"
    - label: "TL;DR"
      link: "/http/routing-advanced"

- label: "Microservices with Deno"
  items:
    - label: "Introduction"
      link: "/microservices/intro"
    - label: "Hello Microservices"
      link: "/microservices/hello"
